---
title: "IGC2"
author: "Yixuan Yang"
date: "6/20/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DT)
library(dplyr)
library(ggplot2)
library(stringr)
```

```{r Readin Unit, include=FALSE}
# getList function will return a list of folder names in a data folder.
getList <- function(directory){
  cwd <- getwd()
  ListOutput = c()
  for(i in c(1:5588)){
    path = paste(cwd,"/inputfiles/",directory,"/",i,"/save/MG94_01_02_nonclockqq_summary.txt", sep = "")
    file = file.exists(path)
    if(file == TRUE){
      ListOutput = append(ListOutput,paste("MG",as.character(i),sep=""))
    }
  }
  return(ListOutput)
}

summaryFile <- function(folder, subfolder){
  savePath <- paste(folder, "/", subfolder, "/save/", sep = "")
  files <- list.files(savePath)
  if(length(files) == 2){
    for(i in files){
      if(grep("summary",i)){
        return(i)
      }
    }
  }
  else{
    return(FALSE)
  }
}

# IGC2Read is a module of List Function. It reads one data outcome as a vector.
IGC2Read <- function(number, directory, file) {
  cwd <- getwd()
  
  path = paste(cwd, "/inputFiles/",directory,"/", number, "/save/", file, sep = "")
  #file = file.exists(path)
 
  v <- scan(path, what = character())
  splitPoint = (length(v) - 1)/2
  value <- as.numeric(v[1:splitPoint])
  names <- v[(splitPoint + 2):length(v)]
  names(value) <- names
  return(value)
 
}

ListFunction <- function(directory,option) {
  folder = paste("inputFiles/", directory, sep = "")
  cases = as.character(sort(as.numeric(list.files(folder))))
  if(option == "List"){
    output = list()
    for(case in cases) {
      file = summaryFile(paste("inputFiles/", directory, sep = ""),case)
      if(file != FALSE){
        name = paste("MG", case, sep = "")#case
        number = case#substr(case, start=3, stop = nchar(case))
        data <- IGC2Read(number, directory, file)
        output[[name]]<- data
      }
      else{
        print(paste(case," do not exist", sep = ""))
      }
    }
    return(output)
  }
  if(option == "Matrix"){
    output = c()
    for(case in cases) {
      file = summaryFile(paste("inputFiles/", directory, sep = ""),case)
      if(file != FALSE){
        name = paste("MG", case, sep = "")
        number = case
        data <- IGC2Read(number, directory, file)
        col <- names(data)
        df <- data.frame(col,data)
        colnames(df) <- c("names", name)
        output = merge(df,output,all=TRUE,sort=FALSE)
        output = merge(df,output,all=TRUE,sort=FALSE)
      }
    }
    return(output) 
  }
}

```

```{r, include=FALSE}
IGC1_Full_noforce_noclock <- ListFunction("IGC1_Full_noforce_noclock","List")
IGC2_Full_noforce_noclock <- ListFunction("IGC2_Full_noforce_noclock","List")
IGC2_Full_noforce_noclock_Matrix <- ListFunction("IGC2_Full_noforce_noclock","Matrix")
```

```{r, echo=FALSE}
# Calculate proportion
proportionSep <- function(case, dataset){
    namelist <- names(dataset[[case]])
    one2two <- c()
    two2one <- c()
    mut <- c()
    for(i in namelist){
      if(str_detect(i,"1->2")){
        if (str_detect(i,"N0")==FALSE){
          one2two <- append(one2two,i)
        }
      }
      
      if(str_detect(i,"2->1")){
        if (str_detect(i,"N0")==FALSE){
          two2one <- append(two2one,i)
        }
      }
      
      if(str_detect(i,"mut")){
        if (str_detect(i,"N0")==FALSE){
          mut <- append(mut,i)
        }
      }
    }
    one2twoSum <- dataset[[case]][one2two]
    two2oneSum <- dataset[[case]][two2one]
    mutSum <- dataset[[case]][mut]
    num <- sum(one2twoSum, two2oneSum)
    den <- sum(one2twoSum, two2oneSum, mutSum)
    p = num/den
    return(p)
}

proportionWhole <- function(dataset){
  cases = names(dataset)
  out = c()
  for(case in cases){
    tryCatch({out = append(out, c(case, proportionSep(case, dataset)))},
             error = function(e){print(case)})
    
  }
  raw <-matrix(out, byrow = TRUE, ncol = 2)
  output <- as.numeric(raw[,2])
  names(output) <- raw[,1]
  return(output)
}
```

```{r, echo=FALSE}
tau.IGC1 <- c()
for(i in IGC1_Full_noforce_noclock){
  tau.IGC1 <- append(tau.IGC1, i[9])
}
names(tau.IGC1) <- names(IGC1_Full_noforce_noclock)
tau.IGC2 <- c()
for(i in IGC2_Full_noforce_noclock){
  tau.IGC2 <- append(tau.IGC2, i[9])
}
names(tau.IGC2) <- names(IGC2_Full_noforce_noclock)
tau.proportion.IGC1 <- proportionWhole(IGC1_Full_noforce_noclock)
tau.proportion.IGC2 <- proportionWhole(IGC2_Full_noforce_noclock)
```


```{r eval=FALSE, include=FALSE}
sort(proportion_IGC2)
datatable(data.frame(proportion_IGC2))
```

```{r eval=FALSE, include=FALSE}
omega = c()
for(i in List2){
  value <- IGC2_Full_noforce_noclock[[i]][8]
  names(value) <- i
  omega = append(omega,value)
}
plot(omega,proportion_IGC2)
cor(omega,proportion_IGC2)
s = lm(proportion_IGC2~omega)
abline(s)
```

```{r echo=FALSE, warning=FALSE, include=FALSE}
IGC1_Swap_noforce_clock <- ListFunction("IGC1_Swap_noforce_clock","List")
IGC1_Unswap_noforce_clock <- ListFunction("IGC1_Unswap_noforce_clock","List")
IGC2_Swap_noforce_clock <- ListFunction("IGC2_Swap_noforce_clock","List")
IGC2_Unswap_noforce_clock <- ListFunction("IGC2_Unswap_noforce_clock","List")
```

```{r, include=FALSE}
# M stand for missing paralog gene dataset
swapTau_M <- c()
swapLL_M  <- c()

for(i in IGC2_Swap_noforce_clock){
  swapTau_M <- append(swapTau_M,i[9])
  swapLL_M  <- append(swapLL_M,i[2])
}
names(swapTau_M) <- names(IGC2_Unswap_noforce_clock)
names(swapLL_M)  <- names(IGC2_Unswap_noforce_clock)

unswapTau_M <- c()
unswapLL_M  <- c()

for(i in IGC2_Unswap_noforce_clock){
  unswapTau_M <- append(unswapTau_M,i[9])
  unswapLL_M  <- append(unswapLL_M,i[2])
}
names(unswapTau_M) <- names(IGC2_Unswap_noforce_clock)
names(unswapLL_M)  <- names(IGC2_Unswap_noforce_clock)

# F stand for full gene dataset
swapTau_F <- c()
swapLL_F  <- c()

for(i in IGC1_Swap_noforce_clock){
  swapTau_F <- append(swapTau_F,i[9])
  swapLL_F  <- append(swapLL_F,i[2])
}
names(swapTau_F) <- names(IGC1_Unswap_noforce_clock)
names(swapLL_F)  <- names(IGC1_Unswap_noforce_clock)

unswapTau_F <- c()
unswapLL_F  <- c()

for(i in IGC1_Unswap_noforce_clock){
  unswapTau_F <- append(unswapTau_F,i[9])
  unswapLL_F  <- append(unswapLL_F,i[2])
}
names(unswapTau_F) <- names(IGC1_Unswap_noforce_clock)
names(unswapLL_F)  <- names(IGC1_Unswap_noforce_clock)

# length
length_M <- c()
for(i in IGC2_Unswap_noforce_clock){
  length_M <- append(length_M,i[1])
}
names(length_M) <- names(IGC2_Unswap_noforce_clock)

length_F <- c()
for(i in IGC1_Unswap_noforce_clock){
  length_F <- append(length_F,i[1])
}
names(length_F) <- names(IGC1_Unswap_noforce_clock)


```


```{r, echo=FALSE, include=FALSE}
tau.dif.M <- unswapTau_M - swapTau_M
ll.dif.M  <- unswapLL_M - swapLL_M
SwapTestM <- matrix(c(length_M,ll.dif.M,tau.dif.M), ncol = 3) %>% as.data.frame()
colnames(SwapTestM)=c("length","ll.dif","tau.dif")

plot(ll.dif.M,tau.dif.M,main="loglikelihood different vs tau different for missing paralog dataset",xlab = "loglikelihood difference",ylab = "tau different", sub = "plot 1")
abline(h=0, col="blue")
abline(v=0, col="red")

tau.dif.F <- unswapTau_F - swapTau_F
ll.dif.F  <- unswapLL_F - swapLL_F
SwapTestF <- matrix(c(length_F,ll.dif.F,tau.dif.F), ncol = 3) %>% as.data.frame()
colnames(SwapTestF)=c("length","ll.dif","tau.dif")

plot(ll.dif.F,tau.dif.F, main="loglikelihood different vs tau different for full paralog dataset",xlab = "loglikelihood difference",ylab = "tau different", sub = "plot 2")
abline(h=0, col="blue")
abline(v=0, col="red")

plot(swapTau_M,unswapTau_M, main = "swap tau vs unswap tau for missing paralog dataset", xlab = "swap tau", ylab = "unswap tau", sub = "plot 3")
abline(coef = c(0,1))

plot(swapTau_F,unswapTau_F, main = "swap tau vs unswap tau for full paralog dataset", xlab = "swap tau", ylab = "unswap tau", sub = "plot 4")
abline(coef = c(0,1))

# influence of length
ggplot(SwapTestM, aes(x=ll.dif, y=tau.dif, color=length)) + geom_point() + scale_color_gradientn(colours = rainbow(5)) + ggtitle("loglikelihood different vs tau different for missing paralog dataset", subtitle = "plot 5") + xlab("loglikelihood different") + ylab("tau different")
ggplot(SwapTestF, aes(x=ll.dif, y=tau.dif, color=length)) + geom_point() + scale_color_gradientn(colours = rainbow(5)) + ggtitle("loglikelihood different vs tau different for full paralog dataset", subtitle = "plot 6") + xlab("loglikelihood different") + ylab("tau different")
```
# histograms
```{r histograms}
hist(tau.IGC1, main = "tau value for no-missing-paralog dataset", sub = paste("Mean: ", round(mean(tau.IGC1),4),"\nStandard Deviation: ", round(sd(tau.IGC1),4), sep = ""), xlab = "")

hist(tau.IGC2, main = "tau value for missing-paralog dataset", sub = paste("Mean: ", round(mean(tau.IGC2),4),"\nStandard Deviation: ", round(sd(tau.IGC2),4), sep = ""), xlab = "")

hist(tau.proportion.IGC1, main = "Proportion of changes due to IGC for no-missing-paralog dataset", sub = paste("Mean: ", round(mean(tau.proportion.IGC1),4),"\nStandard Deviation: ", round(sd(tau.proportion.IGC1),4), sep = ""), xlab = "")

hist(tau.proportion.IGC2, main = "Proportion of changes due to IGC for missing-paralog dataset", sub = paste("Mean: ", round(mean(tau.proportion.IGC2),4),"\nStandard Deviation: ", round(sd(tau.proportion.IGC2),4), sep = ""), xlab = "")

hist(swapTau_F, main = "tau value for swapped no-missing-paralog dataset")
hist(unswapTau_F, main = "tau value for unswapped no-missing-paralog dataset")
hist(swapTau_M, main = "tau value for swapped missing-paralog dataset")
hist(unswapTau_M, main = "tau value for unswapped missing-paralog dataset")

barplot(tau.IGC1, main = "tau value for no-missing-paralog dataset")
barplot(tau.IGC2, main = "tau value for missing-paralog dataset")
barplot(tau.proportion.IGC1, main = "Proportion of changes due to IGC for no-missing-paralog dataset")
barplot(tau.proportion.IGC2, main = "Proportion of changes due to IGC for missing-paralog dataset")
barplot(swapTau_F, main = "tau value for swapped no-missing-paralog dataset")
barplot(unswapTau_F, main = "tau value for unswapped no-missing-paralog dataset")
barplot(swapTau_M, main = "tau value for swapped missing-paralog dataset")
barplot(unswapTau_M, main = "tau value for unswapped missing-paralog dataset")


```

