---
title: "ReadinUnit"
author: "Yixuan Yang"
date: "11/25/2020"
output: html_document
---
```{r}
library(dplyr)
```

```{r}
Readin <- function(list, iterations, caseName) {
    
    columnNames = c()
    data = c()
    for (i in List) {
      
      folderName = paste("/", substr(i, start = 3, stop = nchar(i)), sep = "")
      
      path = paste("./", caseName, folderName, "/save/MG94_01_02_nonclockqq_summary.txt", sep = "")
      numbers <- NA
      tryCatch(numbers <- readLines(path,  n = 89) %>% as.numeric(), error=function(e){
        message(" No data yet.")
      })
      
      variableName = paste(i, iterations, sep = "")
      columnNames <- append(columnNames, variableName)
      data <- cbind(data, numbers)
      
    }
    data <- matrix(data = data, ncol = 45, nrow = 89, byrow = FALSE)
    data.frame(data)
    colnames(data) <- columnNames
    rownames(data) <- NameList
    return(data)
}
MGc4_i1 <- Readin('c4_i1', 'case4(1)')
swcase2 <- Readin(list = swapNameList, 'swc2_i1', caseName = 'swcase2' )
```

```{r}
count = 0
swapSamplePath = './NS2/211/save/MG94_01_02_nonclockqq_summary.txt'
for (i in readLines(swapSamplePath)) {
  count = count + 1
}
NameList4Swap <- readLines(swapSamplePath)
NameList4Swap <- unlist(strsplit(NameList4Swap[count], split = " "))
NameList4Swap <- NameList4Swap[!(NameList4Swap %in% NameList4Swap[1])]



Readin4Swap <- function(list, iterations, caseName) {
    
    columnNames = c()
    data = c()
    for (i in List) {
      
      folderName = paste("/", substr(i, start = 3, stop = nchar(i)), sep = "")
      
      path = paste("./", caseName, folderName, "/save/MG94_01_02_nonclockqq_summary.txt", sep = "")
      numbers <- NA
      tryCatch(numbers <- readLines(path,  n = (count - 1)) %>% as.numeric(), error=function(e){
        message(" No data yet.")
      })
      
      variableName = paste(i, iterations, sep = "")
      columnNames <- append(columnNames, variableName)
      data <- cbind(data, numbers)
      
    }
    data <- matrix(data = data, ncol = 45, nrow = (count - 1), byrow = FALSE)
    data.frame(data)
    colnames(data) <- columnNames
    rownames(data) <- NameList4Swap
    return(data)
}
```

```{r}
Readin4SwapClocked <- function(list, iterations, caseName) {
    
    columnNames = c()
    data = c()
    for (i in List) {
      
      folderName = paste("/", substr(i, start = 3, stop = nchar(i)), sep = "")
      
      path = paste("./", caseName, folderName, "/save/MG94_01_02_clock_summary.txt", sep = "")
      numbers <- NA
      tryCatch(numbers <- readLines(path,  n = (count - 1)) %>% as.numeric(), error=function(e){
        message(" No data yet.")
      })
      
      variableName = paste(i, iterations, sep = "")
      columnNames <- append(columnNames, variableName)
      data <- cbind(data, numbers)
      
    }
    data <- matrix(data = data, ncol = 45, nrow = (count - 1), byrow = FALSE)
    data.frame(data)
    colnames(data) <- columnNames
    rownames(data) <- NameList4Swap
    return(data)
}
```

```{r Read_MG, echo=FALSE}
MG211c4_i1 = NA
MG214c4_i1 = NA
MG222c4_i1 = NA
MG223c4_i1 = NA
MG337c4_i1 = NA
MG479c4_i1 = NA
MG521c4_i1 = NA
MG526c4_i1 = NA
MG561c4_i1 = NA
MG735c4_i1 = NA
MG755c4_i1 = NA
MG852c4_i1 = NA
MG1050c4_i1 = NA
MG1053c4_i1 = NA
MG1215c4_i1 = NA
MG2129c4_i1 = NA
MG2158c4_i1 = NA
MG2210c4_i1 = NA
MG2214c4_i1 = NA
MG2321c4_i1 = NA
MG2358c4_i1 = NA
MG2371c4_i1 = NA
MG2382c4_i1 = NA
MG2861c4_i1 = NA
MG3278c4_i1 = NA
MG3295c4_i1 = NA
MG3309c4_i1 = NA
MG3337c4_i1 = NA
MG3346c4_i1 = NA
MG3347c4_i1 = NA
MG3390c4_i1 = NA
MG3994c4_i1 = NA
MG4025c4_i1 = NA
MG4031c4_i1 = NA
MG4063c4_i1 = NA
MG4268c4_i1 = NA
MG4287c4_i1 = NA
MG4494c4_i1 = NA
MG4553c4_i1 = NA
MG4570c4_i1 = NA
MG4932c4_i1 = NA
MG5153c4_i1 = NA
MG5233c4_i1 = NA
MG5316c4_i1 = NA
MG5550c4_i1 = NA
```

```{r}
MG211c4_i1 = readLines("./case4(1)/211MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
#MG214c4_i1  <- readLines("./case4(1)/214MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MG222c4_i1  <- readLines("./case4(1)/222MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MG223c4_i1  <- readLines("./case4(1)/223MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MG337c4_i1  <- readLines("./case4(1)/337MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
#MG479c4_i1  <- readLines("./case4(1)/479MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
#MG521c4_i1  <- readLines("./case4(1)/521MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
#MG526c4_i1  <- readLines("./case4(1)/526MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
#MG561c4_i1  <- readLines("./case4(1)/561MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
#MG735c4_i1  <- readLines("./case4(1)/735MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MG755c4_i1  <- readLines("./case4(1)/755MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MG852c4_i1  <- readLines("./case4(1)/852MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MG1050c4_i1 <- readLines("./case4(1)/1050MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
#MG1053c4_i1 <- readLines("./case4(1)/1053MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG1215c4_i1 <- readLines("./case4(1)/1215MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG2129c4_i1 <- readLines("./case4(1)/2129MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
#MG2158c4_i1 <- readLines("./case4(1)/2158MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG2210c4_i1 <- readLines("./case4(1)/2210MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG2214c4_i1 <- readLines("./case4(1)/2214MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG2321c4_i1 <- readLines("./case4(1)/2321MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG2358c4_i1 <- readLines("./case4(1)/2358MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG2371c4_i1 <- readLines("./case4(1)/2371MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG2382c4_i1 <- readLines("./case4(1)/2382MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG2861c4_i1 <- readLines("./case4(1)/2861MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG3278c4_i1 <- readLines("./case4(1)/3278MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG3295c4_i1 <- readLines("./case4(1)/3295MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG3309c4_i1 <- readLines("./case4(1)/3309MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG3337c4_i1 <- readLines("./case4(1)/3337MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG3346c4_i1 <- readLines("./case4(1)/3346MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG3347c4_i1 <- readLines("./case4(1)/3347MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG3390c4_i1 <- readLines("./case4(1)/3390MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG3994c4_i1 <- readLines("./case4(1)/3994MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
#MG4025c4_i1 <- readLines("./case4(1)/4025MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
#MG4031c4_i1 <- readLines("./case4(1)/4031MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG4063c4_i1 <- readLines("./case4(1)/4063MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG4268c4_i1 <- readLines("./case4(1)/4268MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG4287c4_i1 <- readLines("./case4(1)/4287MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG4494c4_i1 <- readLines("./case4(1)/4494MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG4553c4_i1 <- readLines("./case4(1)/4553MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG4570c4_i1 <- readLines("./case4(1)/4570MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
#MG4932c4_i1 <- readLines("./case4(1)/4932MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG5153c4_i1 <- readLines("./case4(1)/5153MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
#MG5233c4_i1 <- readLines("./case4(1)/5233MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
#MG5316c4_i1 <- readLines("./case4(1)/5316MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG5550c4_i1 <- readLines("./case4(1)/5550MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()

MGc4_i1 <- cbind(
                   MG211c4_i1, 
                   MG214c4_i1, 
                   MG222c4_i1, 
                   MG223c4_i1, 
                   MG337c4_i1, 
                   MG479c4_i1, 
                   MG521c4_i1, 
                   MG526c4_i1, 
                   MG561c4_i1, 
                   MG735c4_i1, 
                   MG755c4_i1, 
                   MG852c4_i1, 
                   MG1050c4_i1,
                   MG1053c4_i1, 
                   MG1215c4_i1, 
                   MG2129c4_i1, 
                   MG2158c4_i1, 
                   MG2210c4_i1, 
                   MG2214c4_i1, 
                   MG2321c4_i1, 
                   MG2358c4_i1, 
                   MG2371c4_i1, 
                   MG2382c4_i1, 
                   MG2861c4_i1,
                   MG3278c4_i1, 
                   MG3295c4_i1, 
                   MG3309c4_i1, 
                   MG3337c4_i1, 
                   MG3346c4_i1, 
                   MG3347c4_i1, 
                   MG3390c4_i1, 
                   MG3994c4_i1, 
                   MG4025c4_i1, 
                   MG4031c4_i1, 
                   MG4063c4_i1,
                   MG4268c4_i1, 
                   MG4287c4_i1, 
                   MG4494c4_i1, 
                   MG4553c4_i1, 
                   MG4570c4_i1, 
                   MG4932c4_i1, 
                   MG5153c4_i1, 
                   MG5233c4_i1, 
                   MG5316c4_i1, 
                   MG5550c4_i1
                   ) %>% data.frame()
rownames(MGc4_i1) <- NameList
```

```{r nameList, echo=FALSE}
NameList <- readLines(paste( "./data/211MG/save/MG94_01_02_nonclockqq_summary.txt", sep = ""))
NameList <- unlist(strsplit(NameList[90], split=" "))
NameList <- NameList[!(NameList %in% NameList[1])]
```

```{r Read_MG, echo=FALSE}
MG211  <- readLines("./data/211MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MG214  <- readLines("./data/214MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MG222  <- readLines("./data/222MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MG223  <- readLines("./data/223MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MG337  <- readLines("./data/337MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MG479  <- readLines("./data/479MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MG521  <- readLines("./data/521MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MG526  <- readLines("./data/526MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MG561  <- readLines("./data/561MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MG735  <- readLines("./data/735MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MG755  <- readLines("./data/755MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MG852  <- readLines("./data/852MG/save/MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MG1050 <- readLines("./data/1050MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG1053 <- readLines("./data/1053MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG1215 <- readLines("./data/1215MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG2129 <- readLines("./data/2129MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG2158 <- readLines("./data/2158MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG2210 <- readLines("./data/2210MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG2214 <- readLines("./data/2214MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG2321 <- readLines("./data/2321MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG2358 <- readLines("./data/2358MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG2371 <- readLines("./data/2371MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG2382 <- readLines("./data/2382MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG2861 <- readLines("./data/2861MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG3278 <- readLines("./data/3278MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG3295 <- readLines("./data/3295MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG3309 <- readLines("./data/3309MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG3337 <- readLines("./data/3337MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG3346 <- readLines("./data/3346MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG3347 <- readLines("./data/3347MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG3390 <- readLines("./data/3390MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG3994 <- readLines("./data/3994MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG4025 <- readLines("./data/4025MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG4031 <- readLines("./data/4031MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG4063 <- readLines("./data/4063MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG4268 <- readLines("./data/4268MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG4287 <- readLines("./data/4287MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG4494 <- readLines("./data/4494MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG4553 <- readLines("./data/4553MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG4570 <- readLines("./data/4570MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG4932 <- readLines("./data/4932MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG5153 <- readLines("./data/5153MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG5233 <- readLines("./data/5233MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG5316 <- readLines("./data/5316MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG5550 <- readLines("./data/5550MG/save/MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG <- cbind(MG211, MG214, MG222, MG223, MG337, MG479, MG521, MG526, MG561, MG735, MG755, MG852, MG1050,
            MG1053, MG1215, MG2129, MG2158, MG2210, MG2214, MG2321, MG2358, MG2371, MG2382, MG2861,
            MG3278, MG3295, MG3309, MG3337, MG3346, MG3347, MG3390, MG3994, MG4025, MG4031,MG4063,
            MG4268, MG4287, MG4494, MG4553, MG4570, MG4932, MG5153, MG5233, MG5316, MG5550) 
rownames(MG) <- NameList
```

```{r Read_MG_Forced, echo=FALSE}
MF211 <- readLines("/Users/yixuanyang/Desktop/RawData/Force_MG94_pillar211.txt", n = 89) %>% as.numeric()
MF214 <- readLines("/Users/yixuanyang/Desktop/RawData/Force_MG94_pillar214.txt", n = 89) %>% as.numeric()
MF222 <- readLines("/Users/yixuanyang/Desktop/RawData/Force_MG94_pillar222.txt", n = 89) %>% as.numeric()
MF223 <- readLines("/Users/yixuanyang/Desktop/RawData/Force_MG94_pillar223.txt", n = 89) %>% as.numeric()
MF337 <- readLines("/Users/yixuanyang/Desktop/RawData/Force_MG94_pillar337.txt", n = 89) %>% as.numeric()
MF211  <- readLines("./data/211MF/save/Force_MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MF214  <- readLines("./data/214MF/save/Force_MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MF222  <- readLines("./data/222MF/save/Force_MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MF223  <- readLines("./data/223MF/save/Force_MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MF337  <- readLines("./data/337MF/save/Force_MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MF479  <- readLines("./data/479MF/save/Force_MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MF521  <- readLines("./data/521MF/save/Force_MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MF526  <- readLines("./data/526MF/save/Force_MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MF561  <- readLines("./data/561MF/save/Force_MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MF735  <- readLines("./data/735MF/save/Force_MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MF755  <- readLines("./data/755MF/save/Force_MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MF852  <- readLines("./data/852MF/save/Force_MG94_01_02_nonclockqq_summary.txt",  n = 89) %>% as.numeric()
MF1050 <- readLines("./data/1050MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF1053 <- readLines("./data/1053MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF1215 <- readLines("./data/1215MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF2129 <- readLines("./data/2129MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF2158 <- readLines("./data/2158MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF2210 <- readLines("./data/2210MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF2214 <- readLines("./data/2214MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF2321 <- readLines("./data/2321MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF2358 <- readLines("./data/2358MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF2371 <- readLines("./data/2371MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF2382 <- readLines("./data/2382MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF2861 <- readLines("./data/2861MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF3278 <- readLines("./data/3278MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF3295 <- readLines("./data/3295MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF3309 <- readLines("./data/3309MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF3337 <- readLines("./data/3337MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF3346 <- readLines("./data/3346MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF3347 <- readLines("./data/3347MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF3390 <- readLines("./data/3390MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF3994 <- readLines("./data/3994MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF4025 <- readLines("./data/4025MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF4031 <- readLines("./data/4031MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF4063 <- readLines("./data/4063MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF4268 <- readLines("./data/4268MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF4287 <- readLines("./data/4287MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF4494 <- readLines("./data/4494MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF4553 <- readLines("./data/4553MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF4570 <- readLines("./data/4570MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF4932 <- readLines("./data/4932MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF5153 <- readLines("./data/5153MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF5233 <- readLines("./data/5233MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF5316 <- readLines("./data/5316MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MF5550 <- readLines("./data/5550MF/save/Force_MG94_01_02_nonclockqq_summary.txt", n = 89) %>% as.numeric()
MG_Forced <- cbind(MF211, MF214, MF222, MF223, MF337, MF479, MF521, MF526, MF561, MF735, MF755, MF852, 
                   MF1050, MF1053, MF1215, MF2129, MF2158, MF2210, MF2214, MF2321, MF2358, MF2371, MF2382, 
                   MF2861, MF3278, MF3295, MF3309, MF3337, MF3346, MF3347, MF3390, MF3994, MF4025, MF4031, 
                   MF4063, MF4268, MF4287, MF4494, MF4553, MF4570, MF4932, MF5153, MF5233, MF5316, MF5550)
rownames(MG_Forced) <- NameList
```

```{r Read_HKY_Forced, echo=FALSE}
HF211 <- readLines("/Users/yixuanyang/Desktop/RawData/Force_HKY_pillar211.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF214 <- readLines("/Users/yixuanyang/Desktop/RawData/Force_HKY_pillar214.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF222 <- readLines("/Users/yixuanyang/Desktop/RawData/Force_HKY_pillar222.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF223 <- readLines("/Users/yixuanyang/Desktop/RawData/Force_HKY_pillar223.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF337 <- readLines("/Users/yixuanyang/Desktop/RawData/Force_HKY_pillar337.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF211  <- readLines("./data/211HF/save/Force_HKY_01_02_nonclockqq_summary.txt",  n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF214  <- readLines("./data/214HF/save/Force_HKY_01_02_nonclockqq_summary.txt",  n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF222  <- readLines("./data/222HF/save/Force_HKY_01_02_nonclockqq_summary.txt",  n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF223  <- readLines("./data/223HF/save/Force_HKY_01_02_nonclockqq_summary.txt",  n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF337  <- readLines("./data/337HF/save/Force_HKY_01_02_nonclockqq_summary.txt",  n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF479  <- readLines("./data/479HF/save/Force_HKY_01_02_nonclockqq_summary.txt",  n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF521  <- readLines("./data/521HF/save/Force_HKY_01_02_nonclockqq_summary.txt",  n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF526  <- readLines("./data/526HF/save/Force_HKY_01_02_nonclockqq_summary.txt",  n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF561  <- readLines("./data/561HF/save/Force_HKY_01_02_nonclockqq_summary.txt",  n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF735  <- readLines("./data/735HF/save/Force_HKY_01_02_nonclockqq_summary.txt",  n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF755  <- readLines("./data/755HF/save/Force_HKY_01_02_nonclockqq_summary.txt",  n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF852  <- readLines("./data/852HF/save/Force_HKY_01_02_nonclockqq_summary.txt",  n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF1050 <- readLines("./data/1050HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF1053 <- readLines("./data/1053HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF1215 <- readLines("./data/1215HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF2129 <- readLines("./data/2129HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF2158 <- readLines("./data/2158HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF2210 <- readLines("./data/2210HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF2214 <- readLines("./data/2214HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF2321 <- readLines("./data/2321HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF2358 <- readLines("./data/2358HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF2371 <- readLines("./data/2371HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF2382 <- readLines("./data/2382HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF2861 <- readLines("./data/2861HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF3278 <- readLines("./data/3278HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF3295 <- readLines("./data/3295HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF3309 <- readLines("./data/3309HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF3337 <- readLines("./data/3337HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF3346 <- readLines("./data/3346HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF3347 <- readLines("./data/3347HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF3390 <- readLines("./data/3390HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF3994 <- readLines("./data/3994HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF4025 <- readLines("./data/4025HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF4031 <- readLines("./data/4031HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF4063 <- readLines("./data/4063HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF4268 <- readLines("./data/4268HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF4287 <- readLines("./data/4287HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF4494 <- readLines("./data/4494HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF4553 <- readLines("./data/4553HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF4570 <- readLines("./data/4570HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF4932 <- readLines("./data/4932HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF5153 <- readLines("./data/5153HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF5233 <- readLines("./data/5233HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF5316 <- readLines("./data/5316HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HF5550 <- readLines("./data/5550HF/save/Force_HKY_01_02_nonclockqq_summary.txt", n = 88) %>% as.numeric() %>% append(NA, after = 7)
HKY_Forced <- cbind(HF211, HF214, HF222, HF223, HF337, HF479, HF521, HF526, HF561, HF735, HF755, HF852, 
                   HF1050, HF1053, HF1215, HF2129, HF2158, HF2210, HF2214, HF2321, HF2358, HF2371, HF2382, 
                   HF2861, HF3278, HF3295, HF3309, HF3337, HF3346, HF3347, HF3390, HF3994, HF4025, HF4031, 
                   HF4063, HF4268, HF4287, HF4494, HF4553, HF4570, HF4932, HF5153, HF5233, HF5316, HF5550) 
rownames(HKY_Forced) <- NameList
```


















