---
title: "Renamed"
author: "Yixuan Yang"
date: "3/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DT)
library(dplyr)
library(rlist)
#source("ReadinUnit.R")
```

```{r, include=FALSE}
# With clock
NewSwappedClocked1 <- Readin4SwapClocked(NameList4Swap, '', 'NewSwappedClocked1')
NewUnswappedClocked1 <- Readin4SwapClocked(NameList4Swap, '', 'NewUnswappedClocked1')
NewSwappedClocked2 <- Readin4SwapClocked(NameList4Swap, '', 'NewSwappedClocked2')
NewUnswappedClocked2 <- Readin4SwapClocked(NameList4Swap, '', 'NewUnswappedClocked2')
NewSwappedClocked3 <- Readin4SwapClocked(NameList4Swap, '', 'NewSwappedClocked3')
NewUnswappedClocked3 <- Readin4SwapClocked(NameList4Swap, '', 'NewUnswappedClocked3')
```

```{r swap experiment}
NSC3 <- NewSwappedClocked3[c(2,9),] %>% as.matrix() %>% t()
NUC3 <- NewUnswappedClocked3[c(2,9),] %>% as.matrix() %>% t()
NSUC3 <- data.frame(NUC3[,1],NSC3[,1], NUC3[,1]-NSC3[,1], NUC3[,2],NSC3[,2], NUC3[,2]-NSC3[,2])
colnames(NSUC3) <- c('unswap_ll', 'swap_ll', 'll_diference', 'unswap_tau', 'swap_tau', 'tau_difference')

datatable(NSUC3,
          #options = list(pageLength=45), # show all 45 dataset
          caption = "Clock") %>%
  formatRound( columns = 1:6 , 3)

plot(NSUC3[,3], NSUC3[,6],
     #xlim = c(-400, 400),
     xlab = "loglikelihood different",
     ylab = "tau different"
     )
abline(h=0, col="blue")
abline(v=0, col="red")
#fit <- lm(NSUC3[,6]~NSUC3[,3])
#summary(fit)
#abline(fit)

# check loglikelihood differnet small than -25
total = data.frame()
for(i in 1:45){
  if(is.na(NSUC3[i,3])==FALSE){
    if(NSUC3[i,6] != TRUE){
      if(NSUC3[i,3] < 0){
        df <- NSUC3[i,]
        total <- rbind(total,df)
      }
    }
  }
}
datatable(total,
          caption = "check loglikelihood differnet small than 0") %>%
  formatRound( columns = 1:6 , 3)

plot(NSUC3[,4], NSUC3[,5],
     xlab = "unswapped tau",
     ylab = "swapped tau")
abline(coef = c(0,1))

total = data.frame()
for(i in 1:45){
  if(is.na(NSUC3[i,6])==FALSE){
    
    if(NSUC3[i,6] < 0){
      df <- NSUC3[i,]
      total <- rbind(total,df)
    }
    
  }
}
datatable(total,
          caption = "swapped tau larger than unswapped tau") %>%
  formatRound( columns = 1:6 , 3)
```

# nonclock nonforce vs. force tau
```{r include=FALSE}
IGC_Full_noforce_noclock <- Readin(NameList, "", "IGC_Full_noforce_noclock")
IGC_Full_force_noclock <- ReadinF(NameList, "", "IGC_Full_force_noclock")
```

```{r}
form1 <- cbind(IGC_Full_noforce_noclock[2,], IGC_Full_force_noclock[2,], IGC_Full_noforce_noclock[2,]-IGC_Full_force_noclock[2,], IGC_Full_noforce_noclock[9,]) %>% data.frame()
colnames(form1) <- c("ll","ll_tau=0", "difference", "estimated tau")

IGCchangesFull <- function(dataset){
  a = dataset[c(44:57),]
  b = dataset[c(60:73),]
  mutation = dataset[c(76:89),]
  num = colSums(a) + colSums(b)
  den = num + colSums(mutation)
  num/den
}
p <- IGCchangesFull(IGC_Full_noforce_noclock)
form1 <- cbind(form1,p)
form1
```


```{r}
# Proportion of IGC
sort(p)

```

```{r}
datatable(form1
          #options = list(pageLength=45) # show all 45 dataset
          ) %>%
formatRound( columns = 1:5 , 3) 
#hist(form1[,3], xlim = 5)
#sort(form1[,3])
sort(form1[,5]) %>% as.vector()
```

```{r MakePlot}
#TIGC_Full_noforce_noclock <- t(IGC_Full_noforce_noclock)
ot <- lm(IGC_Full_noforce_noclock["omega",]~IGC_Full_noforce_noclock["tau",])$coefficients
pearson <- cor(IGC_Full_noforce_noclock["omega",], IGC_Full_noforce_noclock["tau",], method = "pearson")
plot(IGC_Full_noforce_noclock["omega",], IGC_Full_noforce_noclock["tau",], xlab = "omega", ylab = "tau")
abline(lm( IGC_Full_noforce_noclock["tau",]~IGC_Full_noforce_noclock["omega",]))
sort(IGC_Full_noforce_noclock["tau",])
```
```{r}

#print(IGC_Full_noforce_noclock)
proportion <- IGC_Full_noforce_noclock[11:25,] / colSums(IGC_Full_noforce_noclock[11:25,])

print(proportion)

```








