---
title: "paralogSwapping"
author: "Yixuan Yang"
date: "12/4/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(DT)
library(dplyr)
load("IGC_data1.1.RData")
```

```{r folder names, echo=FALSE}
swapNameList <- c('211', '214', '222', '223', '337', '479', '521', '526', '561', '735', '755', '852', '1050',
            '1053', '1215', '2129', '2158', '2210', '2214', '2321', '2358', '2371', '2382', '2861',
            '3278', '3295', '3309', '3337', '3346', '3347', '3390', '3994', '4025', '4031', '4063',
            '4268', '4287', '4494', '4553', '4570', '4932', '5153', '5233', '5316', '5550')
```

# For this table we use the initial value tau=0.6, omega=0.9, kappa=2.1, inibl=0.1, which is the defalut value in Xiang's software.
# tau=0.01, omega=0.01, kappa=1.0, inibl=0.1

```{r}
SwapTest1 <- Readin4Swap(swapNameList, 'SwapT1', 'SwapTest1')
NonSwapTest1 <- Readin4Swap(swapNameList, 'NSwapT1', 'SwapTest1NA')
SwapTest2 <- Readin4Swap(swapNameList, 'SwapT2', 'SwapTest2')
NonSwapTest2 <- Readin4Swap(swapNameList, 'NSwapT2', 'SwapTest2NA')
NS2 <- Readin4Swap(swapNameList, 'NS2', 'NS2')
NS2unswapped <- Readin4Swap(swapNameList, 'NS2un', 'NS2unswapped')
NS1 <- Readin4Swap(swapNameList, 'NS1', 'NS1')
NS1unswap <- Readin4Swap(swapNameList, 'NS1un', 'NS1unswap')
iniC3 <- Readin4Swap(swapNameList, 'iniC3', 'iniC3')
iniC3unswap <- Readin4Swap(swapNameList, 'iniC3un', 'iniC3unswap')
```

```{r}
newNS2 <- NS2[c(2, 9),] %>% t() %>% as.matrix()
newNS1 <- NS1[c(2, 9),] %>% t() %>% as.matrix()
newNS2unswapped <- NS2unswapped[c(2, 9),] %>% t() %>% as.matrix()
newNS1unswapped <- NS1unswap[c(2, 9),] %>% t() %>% as.matrix()
swCompare1 <- cbind(newNS2, newNS2unswapped, NS2[2,]-NS2unswapped[2,], NS2[9,] - NS2unswapped[9,]) %>% as.data.frame()
row.names(swCompare1) <- List
datatable(swCompare1) %>% 
  formatRound(columns = 1:6, 2)
swCompare2 <- cbind(newNS2, newNS2unswapped, NS2[2,]-NS2unswapped[2,], NS2[9,] - NS2unswapped[9,]) %>% as.data.frame()
row.names(swCompare2) <- List
datatable(swCompare2) %>% 
  formatRound(columns = 1:6, 2)

```


```{r}
newiniC3 <- iniC3[c(2, 9),] %>%  t() %>% as.matrix()
newiniC3unswap <- iniC3unswap[c(2, 9),] %>% t() %>% as.matrix()
new <- cbind(newiniC3, newiniC3unswap) %>% as.data.frame()
row.names(new) <- List
colnames(new) <- c('swap_ll', 'swap_tau', 'unswap_ll', 'unswap_tau')
datatable(new) %>% 
  formatRound(columns = 1:4, 2)
```


```{r}
Swapped_Clocked_1 <- Readin4SwapClocked(NameList4Swap, 'S_C_1', 'Swapped_Clocked_1')
Unswapped_Clocked_1 <- Readin4SwapClocked(NameList4Swap, 'U_C_1', 'Unswapped_Clocked_1')
```

```{r}
newSwapped_Clocked_1 <- Swapped_Clocked_1[c(2, 9),] %>%  t() %>% as.matrix()
newUnswapped_Clocked_1 <- Unswapped_Clocked_1[c(2, 9),] %>% t() %>% as.matrix()
new1 <- cbind(newUnswapped_Clocked_1, newSwapped_Clocked_1) %>% as.data.frame()
rownames(new1) <- List
colnames(new1) <- c('unswap_ll', 'unswap_tau', 'swap_ll', 'swap_tau')
datatable(new1) %>% 
  formatRound(columns = 1:4, 2)
```
```{r}
difll <- new1[,1]-new1[,3]
diftau <- new1[,2]-new1[,4]
plot(difll,diftau,xlab = "difference of log-likelihood", ylab = "difference of estimated tau")
x <- lm(diftau~difll)$coefficient %>% as.numeric()
abline(x, col="red")
new2 <- subset(new1, new1[,2]<0.5)
plot(new2[,2],new2[,4])
```

```{r}
library(readxl)
conf <- read_excel("fish_8spp_WGDfix_bias_nbconverg_CL_Top4_PreDBS8Opt1_bestprobs.xlsx")
rows <- newNumbers + 1 # add 1 for head of the form
conf <- conf[rows,]
conflevel <- conf$BESTPROB
new1 <- cbind(new1, conf$BESTPROB)
plot(difll, conflevel, xlab = "log-likelihood difference", ylab = "confidence level")
```
# Use gene: ENSDARG, ENSTNIG, and ENSLOCG(as outgroup)
# Option: Swap test, Force tau to 0, Clocked
## Note:
If Swapped loglikelihood > Unswapped loglikelihood, the 4th column shows red
3 data are missing
```{r}
New_Swapped_Forced_Clocked_1 <- Readin4SwapFClocked(NameList4Swap, 'NSFC1', 'New_Swapped_Forced_Clocked_1')
New_Unswapped_Forced_Clocked_1 <- Readin4SwapFClocked(NameList4Swap, 'NSFC1', 'New_Unswapped_Forced_Clocked_1')
NSFC1 <- New_Swapped_Forced_Clocked_1[2,] %>% as.matrix()
NUFC1 <- New_Unswapped_Forced_Clocked_1[2,] %>% as.matrix()
NSUFC1 <- cbind(NSFC1, NUFC1, NSFC1-NUFC1)
colnames(NSUFC1) <- c('Swapped_Loglikelihood', 'Unswapped_Loglikelihood', 'difference')
NSUFC1[,3] > 0


datatable(cbind(NSFC1, NUFC1, NSFC1-NUFC1, (NSFC1-NUFC1)>0), colnames = c('Swapped_Loglikelihood', 'Unswapped_Loglikelihood', 'difference', 'Swap>Unswap')) %>%
  formatRound( columns = 1:3 , 3) %>% 
  formatStyle(
    'V4',
    backgroundColor = styleEqual(c(TRUE, FALSE), c('red', 'yellow'))
  )


```

```{r}
# With clock
New_Swapped_Clocked_1 <- Readin4SwapClocked(NameList4Swap, 'NSC1', 'New_Swapped_Clocked_1')
New_Unswapped_Clocked_1 <- Readin4SwapClocked(NameList4Swap, 'NUC1', 'New_Unswapped_Clocked_1')
NSC1 <- New_Swapped_Clocked_1[c(2,9),] %>% as.matrix() %>% t()
NUC1 <- New_Unswapped_Clocked_1[c(2,9),] %>% as.matrix() %>% t()
NSUC1 <- data.frame(NUC1[,1],NSC1[,1], NUC1[,1]-NSC1[,1], NUC1[,2],NSC1[,2], NUC1[,2]-NSC1[,2])
colnames(NSUC1) <- c('unswap_ll', 'swap_ll', 'll_diference', 'unswap_tau', 'swap_tau', 'tau_difference')
datatable(NSUC1, options = list(pageLength=45)) %>%
  formatRound( columns = 1:6 , 3)

# Without clock
New_Swapped_1 <- Readin4Swap(NameList4Swap, 'NS1', 'New_Swapped_1')
New_Unswapped_1 <- Readin4Swap(NameList4Swap, 'NU1', 'New_Unswapped_1')
NS1 <- New_Swapped_1[c(2,9),] %>% as.matrix() %>% t()
NU1 <- New_Unswapped_1[c(2,9),] %>% as.matrix() %>% t()
NSU1 <- data.frame(NU1[,1],NS1[,1], NU1[,1]-NS1[,1], NU1[,2],NS1[,2], NU1[,2]-NS1[,2])
colnames(NSU1) <- c('unswap_ll', 'swap_ll', 'll_diference', 'unswap_tau', 'swap_tau', 'tau_difference')
datatable(NSU1, options = list(pageLength=45)) %>%
  formatRound( columns = 1:6 , 3)
```








